import "@/styles/globals.scss";

import type { Metadata } from "next";

import { inter, sen } from "@/styles/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${sen.variable}`}>{children}</body>
    </html>
  );
}
