import type { Metadata } from "next";
// import { Inter, Sen } from "next/font/google";
import "@/styles/globals.scss";
import { inter, sen } from "@/styles/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${sen.variable}`}>
        <h1>h1 header</h1>
        <h2>h2 header</h2>
        {children}
      </body>
    </html>
  );
}
